
server:
  port: 8070

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/project_yuri"
    username: "root"
    password: "password"

  jpa:
    database: MYSQL
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true

  servlet:
    multipart:
      # Enable multipart uploads
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB
