
server:
  port: 8070

spring:
  datasource:
#    url: jdbc:h2:mem:project_yuri;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    url: jdbc:mysql://localhost:3306/zhangshuai_demo
    username: root
    password: 123456
#    driver-class-name: org.h2.Driver

  jpa:
    database: MYSQL
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        show_sql: true
#        format_sql: true

  servlet:
    multipart:
      # Enable multipart uploads
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB
